use leptos::*;
use std::collections::HashMap;
use crate::api::{GlobalStats, GameStats};
use wordle_engine::SolutionData;

/// The central state of the RUSTLE application, provided via context.
#[derive(Copy, Clone)]
pub struct AppStateContext {
    pub guesses: ReadSignal<Vec<String>>,
    pub set_guesses: WriteSignal<Vec<String>>,
    pub guess_statuses: ReadSignal<Vec<Vec<String>>>,
    pub set_guess_statuses_vec: WriteSignal<Vec<Vec<String>>>,
    pub current_input: ReadSignal<String>,
    pub set_current_input: WriteSignal<String>,
    pub game_won: ReadSignal<bool>,
    pub set_game_won: WriteSignal<bool>,
    pub game_lost: ReadSignal<bool>,
    pub set_game_lost: WriteSignal<bool>,
    pub show_stats: ReadSignal<bool>,
    pub set_show_stats: WriteSignal<bool>,
    pub show_help: ReadSignal<bool>,
    pub set_show_help: WriteSignal<bool>,
    pub jiggle_row: ReadSignal<bool>,
    pub set_jiggle_row: WriteSignal<bool>,
    pub is_revealing_row: ReadSignal<bool>,
    pub set_is_revealing_row: WriteSignal<bool>,
    pub destroy_trigger: ReadSignal<String>,
    pub set_destroy_trigger: WriteSignal<String>,
    pub last_typed_index: ReadSignal<i32>,
    pub set_last_typed_index: WriteSignal<i32>,
    pub theme: ReadSignal<String>,
    pub set_theme: WriteSignal<String>,
    pub hard_mode: ReadSignal<bool>,
    pub set_hard_mode: WriteSignal<bool>,
    pub stats: ReadSignal<GameStats>,
    pub set_stats: WriteSignal<GameStats>,
    pub keyboard_pulse: ReadSignal<(char, String)>,
    pub set_keyboard_pulse: WriteSignal<(char, String)>,
    pub snarky_comment: ReadSignal<String>,
    pub set_snarky_comment: WriteSignal<String>,
    pub is_ng_plus: ReadSignal<bool>,
    pub set_is_ng_plus: WriteSignal<bool>,
    pub ai_pool: ReadSignal<Vec<String>>,
    pub set_ai_pool: WriteSignal<Vec<String>>,
    pub daily_game_done: ReadSignal<bool>,
    pub set_daily_game_done: WriteSignal<bool>,
    pub win_pulse_trigger: ReadSignal<String>,
    pub set_win_pulse_trigger: WriteSignal<String>,
    pub session_points: ReadSignal<i32>,
    pub set_session_points: WriteSignal<i32>,
    pub point_locked_team: ReadSignal<Option<String>>,
    pub set_point_locked_team: WriteSignal<Option<String>>,
    pub global_stats_res: Resource<(), GlobalStats>,
    pub solution_data: Memo<SolutionData>,
    pub char_statuses: Memo<HashMap<char, String>>,
}
