server {
    # Since non-root user cannot bind to port below 1024
    # We will use the docker port 7583 instead of port 80.
    listen       7583;
    listen  [::]:7583;
    server_name  localhost;

    # Location of build files.
    location /react-wordle/ {
        alias  /usr/share/nginx/html/react-wordle/;
        index  index.html index.htm;
        try_files $uri $uri/ /react-wordle/index.html;
    }

    # Redirect root to subpath
    location / {
        return 301 /react-wordle/;
    }

    # Redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
